ALTER TABLE coins SET LOGGED;
ALTER TABLE fees SET LOGGED;
ALTER TABLE balance_actions SET LOGGED;
ALTER TABLE assets SET LOGGED;

ALTER TABLE block_headers SET LOGGED;
ALTER TABLE chain_heads SET LOGGED;
ALTER TABLE crawlers SET LOGGED;

ALTER TABLE transactions SET LOGGED;