ALTER TABLE coins SET UNLOGGED;
ALTER TABLE fees SET UNLOGGED;
ALTER TABLE balance_actions SET UNLOGGED;
ALTER TABLE assets SET UNLOGGED;

ALTER TABLE block_headers SET UNLOGGED;
ALTER TABLE chain_heads SET UNLOGGED;
ALTER TABLE crawlers SET UNLOGGED;

ALTER TABLE transactions SET UNLOGGED;